name: Build AAB
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: android-actions/setup-android@v3
      - run: chmod +x ./gradlew
      - name: Generate Keystore
        run: |
          keytool -genkeypair -noprompt \
            -keystore keystore.jks -alias shqq \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass pass1234 -keypass pass1234 \
            -dname "CN=App,O=App,C=JO"
      - name: Build Signed AAB
        run: |
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=$PWD/keystore.jks \
            -Pandroid.injected.signing.store.password=pass1234 \
            -Pandroid.injected.signing.key.alias=shqq \
            -Pandroid.injected.signing.key.password=pass1234
      - uses: actions/upload-artifact@v4
        with:
          name: shqq-release-aab
          path: app/build/outputs/bundle/release/app-release.aab
